In [1]:
from AgentCreationClassAPR15 import agentsCreator

In [2]:
ac = agentsCreator()

In [3]:
ac.createAgentsAgents()

In [4]:
ac.agentsDS

,bldCode,doorIndex,bldCodeDoorIndex,ProjNumber,aprtmentSize,yearsInBldg,age,lowDiscount,highDiscount,noDiscount,income,rent,own,agentID
0,210_19,1,210_19_1,20180988,70,24,66,0.0,0.0,1.0,10386,1,0,6badc96c-9f4c-11eb-bdcb-acde48001122
1,210_19,2,210_19_2,20180988,70,34,31,0.0,1.0,NaN,6090,1,0,6bae0260-9f4c-11eb-bdcb-acde48001122
2,210_19,3,210_19_3,20180988,70,17,89,0.0,1.0,NaN,6363,0,1,6bae029c-9f4c-11eb-bdcb-acde48001122
3,210_19,4,210_19_4,20180988,70,18,39,0.0,0.0,1.0,13048,0,1,6bae02c4-9f4c-11eb-bdcb-acde48001122
4,210_19,5,210_19_5,20180988,70,25,30,0.0,0.0,1.0,10873,1,0,6bae02e2-9f4c-11eb-bdcb-acde48001122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,201_75,25,201_75_25,502-0368860,87,37,47,0.0,0.0,1.0,13720,0,1,6bae6048-9f4c-11eb-bdcb-acde48001122
893,201_75,26,201_75_26,502-0368860,87,29,73,0.0,0.0,1.0,12257,1,0,6bae605c-9f4c-11eb-bdcb-acde48001122
894,201_75,27,201_75_27,502-0368860,87,39,74,0.0,1.0,NaN,5595,0,1,6bae607a-9f4c-11eb-bdcb-acde48001122
895,201_75,28,201_75_28,502-0368860,87,27,42,0.0,0.0,1.0,12636,0,1,6bae608e-9f4c-11eb-bdcb-acde48001122
896,201_75,29,201_75_29,502-0368860,87,20,60,0.0,0.0,1.0,10073,0,1,6bae60ac-9f4c-11eb-bdcb-acde48001122

In [5]:
ac.agentsDS['age'].mean()

46.31103678929766

In [6]:
ac.agentsDS['age'].mean()

46.31103678929766

In [7]:
import pandas as pd
import numpy as np

In [41]:
columnsC = ['run','ayearsInBldg','aage','lowDiscount','highDiscount','noDiscount','income','rent','own']
agCols = ['yearsInBldg','age','lowDiscount','highDiscount','noDiscount','income','rent','own']
operations = ['mean','mean','sum','sum','sum','mean','sum','sum']
aggList = dict(zip(agCols,operations))
Sensitivity1 = pd.DataFrame(columns=columnsC)

In [42]:
Sensitivity1

Empty DataFrame
Columns: [run, ayearsInBldg, aage, lowDiscount, highDiscount, noDiscount, income, rent, own]
Index: []

In [43]:
for i in range(1000):
    Sensitivity1.loc[i,'run'] = i

In [44]:
def getAggregated():
    ac.createAgentsAgents()
    return ac.agentsDS.agg(aggList).reset_index()[0].values

In [45]:
Sensitivity1 = Sensitivity1.fillna(0)

In [46]:
Sensitivity1.loc[0:2].apply(lambda x: getAggregated(),axis=1)

0    [24.064659977703457, 47.03344481605351, 143.0,...
1    [24.03901895206243, 47.7736900780379, 143.0, 2...
2    [23.522853957636567, 47.4180602006689, 143.0, ...
dtype: object

In [47]:
#Sensitivity1.iloc[0:10,columnsC[1:]] = Sensitivity1.iloc[0:10].apply(lambda x: getAggregated(),axis=1)

## Sensitivity Analysis 1

In [48]:
for i in Sensitivity1.index:
    ac.createAgentsAgents()
    vals =  ac.agentsDS.agg(aggList).values.tolist()
    Sensitivity1.loc[i,columnsC[1:]] = vals

In [32]:
Sensitivity1.loc[0:10]

,run,ayearsInBldg,aage,lowDiscount,highDiscount,noDiscount,income,rent,own
0,0,23.869565,47.266444,143.0,244.0,368.0,9438.602759,318.0,579.0
1,1,24.695652,48.006689,143.0,244.0,368.0,9508.810585,318.0,579.0
2,2,23.668896,47.083612,143.0,244.0,368.0,9465.172176,318.0,579.0
3,3,23.389075,46.285396,143.0,244.0,368.0,9474.702479,318.0,579.0
4,4,24.103679,47.600892,143.0,244.0,368.0,9378.886111,318.0,579.0
5,5,24.103679,47.119287,143.0,244.0,368.0,9536.817308,318.0,579.0
6,6,24.481605,46.282051,143.0,244.0,368.0,9459.671252,318.0,579.0
7,7,23.394649,47.153846,143.0,244.0,368.0,9551.616343,318.0,579.0
8,8,24.329989,46.86845,143.0,244.0,368.0,9495.390345,318.0,579.0
9,9,24.384615,46.498328,143.0,244.0,368.0,9551.963939,318.0,579.0
10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
Sensitivity1.to_excel('agentsSensitivity_april_15.xlsx')

In [1]:
from simRunSensitivityApr15 import simGenerator

In [2]:
sim = simGenerator()

In [3]:
gen = sim.generateSimulation()

In [4]:
gen

,bldCode,doorIndex,bldCodeDoorIndex,ProjNumber,aprtmentSize,yearsInBldg,age,lowDiscount,highDiscount,noDiscount,...,tic,status,Floors,MainCost,cityTax,CostForStaying,ratioCostForStaying,reason_leave,mortgage,rentPrice
0,210_19,1,210_19_1,20180988,70,27.0,16.0,0.0,1.0,0.0,...,0,stay,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
1,210_19,2,210_19_2,20180988,70,26.0,38.0,0.0,0.0,1.0,...,0,stay,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
2,210_19,3,210_19_3,20180988,70,11.0,30.0,0.0,0.0,1.0,...,0,stay,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
3,210_19,4,210_19_4,20180988,70,7.0,33.0,0.0,0.0,1.0,...,0,stay,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
4,210_19,5,210_19_5,20180988,70,8.0,40.0,0.0,0.0,1.0,...,0,stay,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,201_75_rr,25,201_75_rr_25,502-0368860,112,0.0,35.0,0.0,0.0,1.0,...,32,New Comers,32.0,450.0,608.16,8898.16,0.37296,NaN,0,NaN
4843,201_75_rr,26,201_75_rr_26,502-0368860,112,0.0,25.0,0.0,0.0,1.0,...,32,New Comers,32.0,450.0,608.16,9406.16,0.35773,NaN,8348,NaN
4844,201_75_rr,27,201_75_rr_27,502-0368860,112,0.0,36.0,0.0,0.0,1.0,...,32,New Comers,32.0,450.0,608.16,9350.16,0.324234,NaN,8292,NaN
4845,201_75_rr,28,201_75_rr_28,502-0368860,112,0.0,53.0,0.0,0.0,1.0,...,32,New Comers,32.0,450.0,608.16,9427.16,0.341411,NaN,8369,NaN
4846,201_75_rr,29,201_75_rr_29,502-0368860,112,0.0,48.0,0.0,0.0,1.0,...,32,New Comers,32.0,450.0,608.16,8898.16,0.372741,NaN,0,NaN

In [1]:
from analyzeSensetivity import senAnalyze

In [2]:
import numpy as np

In [3]:
a = senAnalyze()

In [5]:
a.generate_analyze(True)
a.res2

,aprtmentSizeMean,ProjNumber,yearsInBldgMean,aprtmentSizeMeanStay,aprtmentSizeNewComer,AgeMean,AgeMeanNew,AgeMeanStay,AgeOldStayNew,AgeYoungStayNew,AgeOldStay,AgeYoungStay,AgeOldNew,AgeYoungNew,IncomeHighStay,IncomeMedStay,IncomeLowStay,IncomeHighNew,IncomeMedNew,IncomeLowNew,IncomeHighStayNew,IncomeMedStayNew,IncomeLowStayNew,meanIncomeStay,meanIncomeNewComers,meanIncomeStay_N_new,rentCount,ownCount,rentStayCount,rentNewCount,ownStayCount,ownNewCount,TotalAgentsCount,prjectType,tic,stay,new comers,CostForStaying,rentPrice,leave
0,74.914158,NaN,23.526198,NaN,NaN,48.35786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,318.0,579.0,NaN,NaN,NaN,NaN,897.0,0,0,897.0,NaN,NaN,0.0,0.0
1,75.337691,20180988,22.810458,75.081448,82.0,48.409586,48.470588,48.40724,255.0,663.0,248.0,636.0,7.0,27.0,0.0,369.0,515.0,23.0,11.0,0.0,23.0,380.0,515.0,7699.251131,20246.763158,8163.973799,321.0,597.0,310.0,11.0,574.0,23.0,918.0,1,1,884.0,34.0,255.62817,0.0,13.0
2,75.616379,20100133,22.141164,75.175115,82.0,48.483836,48.483333,48.483871,256.0,672.0,243.0,625.0,13.0,47.0,0.0,364.0,504.0,40.0,20.0,0.0,40.0,384.0,504.0,7697.449309,20174.97807,8504.186082,325.0,603.0,304.0,21.0,564.0,39.0,928.0,1,2,868.0,60.0,441.070496,0.0,29.0
3,75.587302,20180812,21.439153,75.629977,75.186813,48.366138,49.307692,48.265808,256.0,689.0,236.0,618.0,20.0,71.0,0.0,356.0,498.0,40.0,51.0,0.0,40.0,407.0,498.0,7658.194379,18781.043378,8729.283542,324.0,621.0,297.0,27.0,557.0,64.0,945.0,1,3,854.0,91.0,606.108847,0.0,43.0
4,76.027112,20181092,20.61731,75.605232,79.033898,48.442127,50.067797,48.214031,258.0,701.0,231.0,610.0,27.0,91.0,0.0,350.0,491.0,66.0,52.0,0.0,66.0,402.0,491.0,7639.385256,19569.922391,9107.376269,329.0,630.0,291.0,38.0,550.0,80.0,959.0,1,4,841.0,118.0,810.857831,0.0,56.0
5,76.627907,20171974,19.788675,75.894231,80.515924,48.542973,50.254777,48.219952,264.0,725.0,228.0,604.0,36.0,121.0,0.0,346.0,486.0,98.0,59.0,0.0,98.0,405.0,486.0,7620.582933,19983.318304,9583.120297,339.0,650.0,286.0,53.0,546.0,104.0,989.0,2,5,832.0,157.0,1067.265228,0.0,65.0
6,77.235471,20180345,18.986974,75.895392,82.753846,48.568136,49.979487,48.225405,265.0,733.0,219.0,584.0,46.0,149.0,0.0,335.0,468.0,134.0,61.0,0.0,134.0,396.0,468.0,7579.066002,20410.880837,10086.284332,342.0,656.0,274.0,68.0,529.0,127.0,998.0,1,6,803.0,195.0,1351.47013,0.0,94.0
7,77.491107,20140556,18.318182,76.022843,82.65625,48.507905,49.138393,48.32868,264.0,748.0,215.0,573.0,49.0,175.0,0.0,334.0,454.0,154.0,70.0,0.0,154.0,404.0,454.0,7594.006345,20421.369008,10433.264484,347.0,665.0,268.0,79.0,520.0,145.0,1012.0,1,7,788.0,224.0,1526.267777,0.0,109.0
8,77.348566,20170076,16.585125,76.155612,80.165663,48.468638,48.879518,48.294643,286.0,830.0,213.0,571.0,73.0,259.0,0.0,332.0,452.0,202.0,130.0,0.0,202.0,462.0,452.0,7582.216837,19968.597733,11267.054164,385.0,731.0,266.0,119.0,518.0,213.0,1116.0,2,8,784.0,332.0,1989.793002,0.0,113.0
9,85.773035,502-0196659,9.708672,78.567308,91.050469,47.345528,46.913146,47.935897,328.0,1148.0,162.0,462.0,166.0,686.0,0.0,312.0,312.0,722.0,130.0,0.0,722.0,442.0,312.0,8386.044872,22327.268254,16433.417719,484.0,992.0,176.0,308.0,448.0,544.0,1476.0,3,9,624.0,852.0,4387.32479,0.0,273.0
10,86.497671,20150857,9.351963,78.521951,92.021396,47.361943,46.917793,48.003252,334.0,1169.0,160.0,455.0,174.0,714.0,0.0,309.0,306.0,758.0,130.0,0.0,758.0,439.0,306.0,8385.627642,22520.153894,16736.565308,492.0,1011.0,172.0,320.0,443.0,568.0,1503.0,2,10,615.0,888.0,4533.625376,0.0,282.0
12,87.007213,20140231,9.163934,78.408867,92.723799,47.440656,47.045852,48.034483,336.0,1189.0,158.0,451.0,178.0,738.0,0.0,308.0,301.0,786.0,130.0,0.0,786.0,438.0,301.0,8401.520525,22671.873219,16973.08975,499.0,1026.0,172.0,327.0,437.0,589.0,1525.0,2,12,609.0,916.0,4641.627895,0.0,288.0
13,87.199229,20150274,8.891388,78.467554,92.694241,47.377249,46.975916,48.014975,342.0,1214.0,156.0,445.0,186.0,769.0,0.0,303.0,298.0,822.0,133.0,0.0,822.0,436.0,298.0,8370.391015,22646.834858,17132.604299,514.0,1042.0,168.0,346.0,433.0,609.0,1556.0,1,13,601.0,955.0,4736.278033,0.0,296.0
14,86.808696,20120894,8.484472,78.878583,91.432645,47.291925,46.882006,47.994941,348.0,1262.0,153.0,440.0,195.0,822.0,0.0,300.0,293.0,834.0,183.0,0.0,834.0,483.0,293.0,8364.185497,22365.77858,17208.670072,529.0,1081.0,166.0,363.0,427.0,654.0,1610.0,1,14,593.0,1017.0,4810.893056,0.0,304.0
15,87.07025,20181295,8.068418,78.968696,91.456685,47.359805,47.02919,47.970435,352.0,1285.0,148.0,427.0,204.0,858.0,0.0,297.0,278.0,879.0,183.0,0.0,879.0,480.0,278.0,8397.975652,22377.241625,17466.992428,537.0,1100.0,159.0,378.0,416.0,684.0,1637.0,1,15,575.0,1062.0,4941.320941,0.0,322.0
16,87.133172,20140060,7.854116,79.228723,91.230699,47.335351,47.104779,47.780142,354.0,1298.0,143.0,421.0,211.0,877.0,0.0,291.0,273.0,896.0,192.0,0.0,896.0,483.0,273.0,8398.920213,22333.454891,17576.14402,542.0,1110.0,153.0,389.0,411.0,699.0,1652.0,1,16,564.0,1088.0,5003.837276,0.0,333.0
17,87.306539,20110270,7.510498,79.273224,91.251342,47.277145,47.081395,47.675774,352.0,1315.0,138.0,411.0,214.0,904.0,0.0,288.0,261.0,923.0,195.0,0.0,923.0,483.0,261.0,8420.712204,22323.353333,17744.739068,547.0,1120.0,148.0,399.0,401.0,719.0,1667.0,1,17,549.0,1118.0,5095.566683,0.0,348.0
18,87.517282,20140467,7.184148,78.994382,91.495629,47.338498,47.144231,47.754682,355.0,1323.0,135.0,399.0,220.0,924.0,0.0,281.0,253.0,949.0,195.0,0.0,949.0,476.0,253.0,8403.189139,22355.010052,17915.038439,551.0,1127.0,142.0,409.0,392.0,735.0,1678.0,1,18,534.0,1144.0,5190.953445,0.0,363.0
19,87.795603,20160319,6.755793,78.550296,91.781463,47.349376,47.168367,47.769231,352.0,1331.0,127.0,380.0,225.0,951.0,0.0,273.0,234.0,981.0,195.0,0.0,981.0,468.0,234.0,8431.149901,22404.603316,18195.13161,558.0,1125.0,135.0,423.0,372.0,753.0,1683.0,1,19,507.0,1176.0,5335.683042,0.0,390.0
20,88.13639,20141182,6.477954,78.167002,92.251661,47.185185,47.048173,47.517103,349.0,1352.0,121.0,376.0,228.0,976.0,0.0,270.0,227.0,1009.0,195.0,0.0,1009.0,465.0,227.0,8432.637827,22491.911851,18384.058124,561.0,1140.0,130.0,431.0,367.0,773.0,1701.0,1,20,497.0,1204.0,5429.044891,0.0,400.0
21,92.057752,502-0654715,4.976067,77.20362,96.493919,47.190947,47.260135,46.959276,386.0,1536.0,98.0,344.0,288.0,1192.0,0.0,237.0,205.0,1285.0,195.0,0.0,1285.0,432.0,205.0,8254.31448,23360.661895,19886.673572,639.0,1283.0,110.0,529.0,332.0,951.0,1922.0,3,21,442.0,1480.0,6163.226644,0.0,455.0
22,93.037688,502-0316752,4.79799,77.122727,97.555484,47.046734,47.076129,46.943182,393.0,1597.0,97.0,343.0,296.0,1254.0,0.0,235.0,205.0,1355.0,195.0,0.0,1355.0,430.0,205.0,8239.593182,23575.014041,20184.26772,665.0,1325.0,108.0,557.0,332.0,993.0,1990.0,3,22,440.0,1550.0,6293.251563,0.0,457.0
23,94.616507,502-0201483,4.166439,77.032941,98.843326,46.75969,46.825792,46.484706,427.0,1766.0,89.0,336.0,338.0,1430.0,0.0,227.0,198.0,1573.0,195.0,0.0,1573.0,422.0,198.0,8202.016471,23836.761506,20806.772158,743.0,1450.0,103.0,640.0,322.0,1128.0,2193.0,3,23,425.0,1768.0,6584.792253,0.0,472.0
24,95.538598,502-0583948,3.978261,76.536058,99.839499,46.735138,46.826442,46.331731,440.0,1814.0,87.0,329.0,353.0,1485.0,0.0,221.0,195.0,1643.0,195.0,0.0,1643.0,416.0,195.0,8146.216346,24049.938964,21114.735499,763.0,1491.0,101.0,662.0,315.0,1176.0,2254.0,3,24,416.0,1838.0,6723.057635,0.0,481.0
25,96.063356,502-0424911,3.63399,76.5225,100.100723,46.755993,46.894112,46.0875,454.0,1882.0,82.0,318.0,372.0,1564.0,0.0,213.0,187.0,1741.0,195.0,0.0,1741.0,408.0,187.0,8121.3925,24111.098671,21373.135285,791.0,1545.0,91.0,700.0,309.0,1236.0,2336.0,3,25,400.0,1936.0,6849.443455,0.0,497.0
26,97.756672,502-0147678,3.306907,76.891414,101.59619,46.806122,46.952602,46.010101,502.0,2046.0,80.0,316.0,422.0,1730.0,0.0,210.0,186.0,1957.0,195.0,0.0,1957.0,405.0,186.0,8109.487374,24406.982256,21874.090587,871.0,1677.0,91.0,780.0,305.0,1372.0,2548.0,3,26,396.0,2152.0,7073.789133,0.0,501.0
27,97.825797,502-0178285,2.497035,81.653614,100.095097,46.889918,47.046492,45.774096,533.0,2165.0,64.0,268.0,469.0,1897.0,0.0,189.0,143.0,2134.0,232.0,0.0,2134.0,421.0,143.0,8479.975904,24098.770688,22176.813731,909.0,1789.0,55.0,854.0,277.0,1512.0,2698.0,3,27,332.0,2366.0,7250.297409,0.0,565.0
28,98.080758,502-0317495,1.999298,86.115523,99.369895,46.574087,46.88837,43.65704,538.0,2310.0,40.0,237.0,498.0,2073.0,0.0,175.0,102.0,2332.0,239.0,0.0,2332.0,414.0,102.0,8978.476534,23949.93353,22493.791118,960.0,1888.0,30.0,930.0,247.0,1641.0,2848.0,3,28,277.0,2571.0,7417.506675,0.0,620.0
29,97.825075,502-0189720,1.767875,88.51751,98.694909,46.635185,46.985455,42.88716,571.0,2436.0,33.0,224.0,538.0,2212.0,0.0,165.0,92.0,2502.0,248.0,0.0,2502.0,413.0,92.0,9006.264591,23820.459895,22554.331463,1012.0,1995.0,18.0,994.0,239.0,1756.0,3007.0,3,29,257.0,2750.0,7465.875035,0.0,640.0
30,97.927957,502-0316588,1.49219,92.114035,98.383637,46.503985,46.841526,42.197368,592.0,2545.0,27.0,201.0,565.0,2344.0,0.0,150.0,78.0,2660.0,249.0,0.0,2660.0,399.0,78.0,9074.97807,23756.662536,22689.584417,1060.0,2077.0,10.0,1050.0,218.0,1859.0,3137.0,3,30,228.0,2909.0,7547.04321,0.0,669.0
31,98.01206,20180845,1.401777,92.938967,98.37985,46.504284,46.854323,41.676056,595.0,2556.0,23.0,190.0,572.0,2366.0,0.0,140.0,73.0,2689.0,249.0,0.0,2689.0,389.0,73.0,8955.276995,23754.890133,22754.47198,1064.0,2087.0,4.0,1060.0,209.0,1878.0,3151.0,1,31,213.0,2938.0,7588.925608,0.0,684.0
32,98.669434,502-0368860,1.234932,94.447368,98.931417,46.514453,46.880144,40.621053,611.0,2641.0,15.0,175.0,596.0,2466.0,0.0,126.0,64.0,2813.0,249.0,0.0,2813.0,375.0,64.0,8836.905263,23878.428203,22999.618437,1098.0,2154.0,0.0,1098.0,190.0,1964.0,3252.0,3,32,190.0,3062.0,7707.22552,0.0,707.0

In [7]:
a.res2.to_excel('aggregated_results_by_project_april17.xlsx')

In [37]:
colsKeep = ['tic','stay','new comers','AgeMeanNew','AgeMeanStay','AgeMean','meanIncomeStay','meanIncomeNewComers','meanIncomeStay_N_new']

In [39]:
analyzeDF = a.res2[colsKeep].copy()

In [40]:
analyzeDF['test'] = 0

In [48]:
for i in range(500):
    if (np.mod(i,10)==0):
        print('Epoch:',i)
    a = senAnalyze()
    a.generate_analyze()
    epoch = a.res2[colsKeep].copy()
    epoch['test'] = i 
    if (i==0):
        analyzeDF.loc[analyzeDF['test']==0,:] = epoch
    else:
        analyzeDF = analyzeDF.append(epoch)
analyzeDF.reset_index(drop=True,inplace=True)

Epoch: 0
Epoch: 10
Epoch: 20
Epoch: 30
Epoch: 40
Epoch: 50
Epoch: 60
Epoch: 70
Epoch: 80
Epoch: 90
Epoch: 100
Epoch: 110
Epoch: 120
Epoch: 130
Epoch: 140
Epoch: 150
Epoch: 160
Epoch: 170
Epoch: 180
Epoch: 190
Epoch: 200
Epoch: 210
Epoch: 220
Epoch: 230
Epoch: 240
Epoch: 250
Epoch: 260
Epoch: 270
Epoch: 280
Epoch: 290
Epoch: 300
Epoch: 310
Epoch: 320
Epoch: 330
Epoch: 340
Epoch: 350
Epoch: 360
Epoch: 370
Epoch: 380
Epoch: 390
Epoch: 400
Epoch: 410
Epoch: 420
Epoch: 430
Epoch: 440
Epoch: 450
Epoch: 460
Epoch: 470
Epoch: 480
Epoch: 490

In [49]:

analyzeDF.to_excel('analyzeResults_april_15_1.xlsx')

In [46]:
analyzeDF

,tic,stay,new comers,AgeMeanNew,AgeMeanStay,AgeMean,meanIncomeStay,meanIncomeNewComers,meanIncomeStay_N_new,test
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,883.0,35.0,45.942857,47.472254,47.413943,7572.169875,20414.97594,8061.819344,0.0
2,2,870.0,58.0,48.655172,47.645977,47.709052,7579.55977,20310.261343,8375.228618,0.0
3,3,860.0,85.0,49.352941,47.569767,47.730159,7571.784884,19015.517647,8601.115344,0.0
4,4,847.0,112.0,49.8125,47.670602,47.920751,7556.461629,19578.868891,8960.53839,0.0
...,...,...,...,...,...,...,...,...,...,...
1607,28,286.0,2562.0,47.081187,41.982517,46.569171,8278.594406,24029.724794,22447.975043,49.0
1608,29,264.0,2743.0,47.225665,41.738636,46.743931,8376.590909,23896.027093,22533.495948,49.0
1609,30,236.0,2901.0,47.103757,41.355932,46.671342,8314.228814,23823.204866,22656.447343,49.0
1610,31,220.0,2931.0,47.092119,40.9,46.659791,8106.777273,23816.461761,22719.625649,49.0
1611,32,195.0,3057.0,47.106313,39.302564,46.638376,7917.246154,23933.246836,22972.877792,49.0

In [47]:
epoch

,tic,stay,new comers,AgeMeanNew,AgeMeanStay,AgeMean,meanIncomeStay,meanIncomeNewComers,meanIncomeStay_N_new,test
1,1,882.0,36.0,46.611111,47.420635,47.388889,7594.588435,20434.907895,8098.130375,49
2,2,866.0,62.0,47.516129,47.510393,47.510776,7583.010393,20239.449915,8428.591481,49
3,3,854.0,91.0,45.912088,47.484778,47.333333,7557.764637,18973.218045,8657.030521,49
4,4,839.0,120.0,44.725,47.287247,46.966632,7523.755662,19793.351754,9059.054443,49
5,5,831.0,158.0,46.044304,47.361011,47.150657,7522.5716,20056.040973,9524.885211,49
6,6,805.0,193.0,46.134715,47.392547,47.149299,7495.840994,20436.937278,9998.47785,49
7,7,789.0,223.0,46.946188,47.250951,47.183794,7508.698352,20396.26009,10348.546443,49
8,8,786.0,330.0,46.984848,47.21374,47.146057,7509.473282,19999.290032,11202.698665,49
9,9,632.0,844.0,47.485782,45.85443,46.787263,8174.221519,22309.324738,16256.895717,49
10,10,622.0,881.0,47.409762,45.927653,46.796407,8162.395498,22518.263337,16577.245509,49
12,12,616.0,909.0,47.348735,45.821429,46.731803,8170.774351,22655.456951,16804.594996,49
13,13,610.0,946.0,47.160677,45.67541,46.578406,8165.55082,22645.203739,16968.733121,49
14,14,602.0,1008.0,47.127976,45.561462,46.542236,8141.503322,22381.116802,17056.739588,49
15,15,580.0,1057.0,47.124882,45.708621,46.623091,8143.386207,22378.92526,17335.178986,49
16,16,567.0,1085.0,47.22765,45.650794,46.686441,8121.559083,22335.540626,17457.013062,49
17,17,552.0,1115.0,47.286996,45.701087,46.761848,8138.894928,22337.844937,17636.093045,49
18,18,540.0,1138.0,47.370826,45.644444,46.815256,8146.075926,22371.390759,17793.518286,49
19,19,510.0,1173.0,47.398124,45.543137,46.836007,8111.396078,22443.315565,18100.30966,49
20,20,501.0,1200.0,47.323333,45.740519,46.857143,8117.774451,22529.712281,18284.926359,49
21,21,446.0,1476.0,47.166667,45.26009,46.724246,7971.038117,23427.401369,19840.753081,49
22,22,444.0,1546.0,47.073739,45.308559,46.679899,7946.736486,23634.448968,20134.275932,49
23,23,432.0,1761.0,46.821124,44.974537,46.457364,7910.576389,23900.17514,20750.377301,49
24,24,423.0,1831.0,46.753687,44.881797,46.402396,7873.1513,24113.681164,21065.879863,49
25,25,407.0,1929.0,46.67548,44.226044,46.248716,7804.990172,24167.66874,21316.808219,49
26,26,401.0,2147.0,46.728924,44.087282,46.313187,7762.0399,24465.09281,21836.394138,49
27,27,337.0,2361.0,46.793731,43.35905,46.364715,7943.74184,24176.380637,22148.804924,49
28,28,286.0,2562.0,47.081187,41.982517,46.569171,8278.594406,24029.724794,22447.975043,49
29,29,264.0,2743.0,47.225665,41.738636,46.743931,8376.590909,23896.027093,22533.495948,49
30,30,236.0,2901.0,47.103757,41.355932,46.671342,8314.228814,23823.204866,22656.447343,49
31,31,220.0,2931.0,47.092119,40.9,46.659791,8106.777273,23816.461761,22719.625649,49
32,32,195.0,3057.0,47.106313,39.302564,46.638376,7917.246154,23933.246836,22972.877792,49