In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np
import pyproj

pyproj.datadir.set_data_dir('/Users/shai/anaconda3/envs/geo_env/share/proj')

In [38]:
script = pd.read_excel('bldgMapping_March_4.xlsx')

In [39]:
script

,Unnamed: 0,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC
0,15,210_19,210_19_a,1,20180988,1,1,17
1,16,210_14,210_14_a,1,20100133,2,2,18
2,14,208_32,208_32_a,1,20180812,3,3,19
3,19,210_3,210_3_a,1,20181092,4,4,20
4,20,210_35,210_35_r,2,20171974,5,20,13
5,17,210_12,210_12_a,1,20180345,6,5,21
6,18,210_10,210_10_a,1,20140556,7,6,22
7,22,"211_19,211_20,211_19","211_22_r,211_20_r,211_19_r",2,20170076,8,21,14
8,26,"224_3,220_7,220_3,210_34,210_36,220_5,210_32_2...","220_3_224_3_rr,210_30_210_32_rr,220_5_rr,220_7...",3,502-0196659,9,24,1
9,21,215_6,215_6_r,2,20150857,10,22,15
10,33,"221_4_221_2,221_6","216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2
11,1,216_4,216_4_a,1,20141086,12,7,23
12,2,209_6,209_6_r,2,20140231,13,23,16
13,0,215_22,215_22_a,1,20140882,14,8,24
14,5,210_11,210_11_a,1,20150274,15,9,25
15,6,216_3,216_3_a,1,20141190,16,10,26
16,3,209_8_209_10_209_12,209_8_209_10_209_12_a,1,20120894,17,11,27
17,4,208_12,208_12_a,1,20181295,18,12,28
18,9,220_4,220_4_a,1,20131419,19,13,29
19,7,215_18,215_18_a,1,20140060,20,14,30
20,8,215_24,215_24_a,1,20110270,21,15,31
21,12,209_4,209_4_a,1,20180845,22,16,32
22,13,217_5,217_5_a,1,20140467,23,17,33
23,10,212_53,212_53_a,1,20160319,24,18,34
24,11,209_29,209_29_a,1,20141182,25,19,35
25,34,201_75,201_75_rr,3,502-0368860,26,26,3
26,23,"212_61,212_61,212_61,216_8","212_59_rr,212_61_1_rr,212_61_rr",3,502-0654715,27,27,4
27,29,"209_30,209_32,209_30,209_32","209_32_1_rr,209_32_rr",3,502-0316752,28,28,5
28,27,"215_12,215_14,102_3,215_12","215_14_rr,215_14_102_3_215_12_rr",3,502-0201483,29,29,6
29,25,212_63,"212_63_rr,212_63_1_rr",3,502-0583948,30,30,7
30,24,"201_7,201_9,201_9,201_9","201_7_rr,201_9_rr",3,502-0424911,31,31,8
31,28,220_4,"215_2_rr,220_2_rr",3,502-0147678,32,32,9
32,30,"225_8,225_6,210_8,225_6","225_6_rr,225_8_rr",3,502-0178285,33,33,10
33,31,"211_9,210_18,210_16,211_11,211_7","210_18_rr,211_11_rr",3,502-0317495,34,34,11
34,32,"221_30_211_26,211_25_211_27_211_29,221_22","221_22_221_29_rr,211_30_211_26_rr,211_27_rr",3,502-0189720,35,35,12

In [40]:
study = pd.read_excel('study_with_type_March_2021.xlsx')

In [42]:
study.head()

,Unnamed: 0,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,PepoleLiving,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2,CheckAppartments,Address_key,plan_numbe,Address_Heb_first,plan_num,Projecttype,Before_app,after_app,ResidentialAreaBefore,Need correction,Comment
0,18,208_12,2,49,16,2,109,53,25,56,22,34,39.285714,110,83,80,80,10,16,8,8,8,17,7,0.348805,24,0.666667,0.333333,0.333333,0.333333,0.708333,2.333333,True,208_12,20181295,"הלפר 12, בת ים",20181295,1,24,51,1992,NaN,NaN
1,19,208_15,2,51,16,4,100,50,23,72,24,48,33.333333,80,72,60,70,6,14,12,2,13,17,10,0.375359,27,0.518519,0.074074,0.444444,0.481481,0.629630,2.666667,True,208_15,20181114,"הלפר 15, בת ים",20181114,1,27,54,1944,NaN,NaN
2,20,208_32,2,33,10,5,89,46,23,35,11,24,31.428571,90,62,30,50,17,7,4,3,10,10,7,0.284133,17,0.411765,0.176471,0.235294,0.588235,0.588235,2.058824,True,208_32,20180812,"הלפר 32, בת ים",20180812,1,17,34,1054,NaN,NaN
3,2,209_29,2,48,17,9,96,55,23,38,13,25,34.210526,100,87,70,100,13,7,5,2,5,7,5,0.308843,12,0.583333,0.166667,0.416667,0.416667,0.583333,3.166667,True,209_29,20141182,"ארלוזורוב 29, בת ים",20141182,1,12,28,1044,NaN,NaN
4,8,209_8,2,50,10,2,94,39,23,40,7,33,17.500000,90,70,60,60,12,5,1,4,11,14,2,0.073787,16,0.312500,0.250000,0.062500,0.687500,0.875000,2.500000,True,209_8,20120894,"ארלוזורוב 8, בת ים",20120894,1,16,24,1120,statistics fix,"3 buildings Tama 38, staitistics are on one bu..."

In [43]:
study.columns

Index(['Unnamed: 0', 'Row Labels', 'min_living_till_2020',
       'max_living_till_2020', 'avg_living_till_2020', 'Min_age_2020',
       'Max_age_2020', 'Average_age_2020', 'StdDev_age_2020', 'PepoleLiving',
       'Above_65', 'Under_65', 'percent_above_65', 'Area_round_max',
       'Area_round_mean', 'Area_round_min', 'Area_round_mode',
       'Area_round_std', 'Discount_sum', 'High_discount_sum',
       'Low_Discount_35_sum', 'No_Discount_sum', 'Owner_sum', 'Renter_sum',
       'discount_rate_mean', 'total_appartments', 'discount_percent',
       'Low_discount', 'High_discount', 'No_discount', 'Owner_Percent',
       'houseHold2', 'CheckAppartments', 'Address_key', 'plan_numbe',
       'Address_Heb_first', 'plan_num', 'Projecttype', 'Before_app',
       'after_app', 'ResidentialAreaBefore', 'Need correction', 'Comment'],
      dtype='object')

In [44]:
studyGB = study.groupby('plan_num')

In [63]:
studyGBAgg = studyGB.agg({'Row Labels':'count','min_living_till_2020':'mean','max_living_till_2020':'mean','avg_living_till_2020':'mean',
            'Min_age_2020':'mean','Max_age_2020':'mean','Average_age_2020':'mean','StdDev_age_2020':'mean',
             'Before_app':'mean','after_app':'mean','Above_65':'mean','Under_65':'mean', 'percent_above_65':'mean',
             'Area_round_max':'mean','Area_round_mean':'mean', 'Area_round_min':'mean', 'Area_round_mode':'mean',
       'Area_round_std':'mean','Discount_sum':'mean', 'High_discount_sum':'mean',
       'Low_Discount_35_sum':'mean', 'No_Discount_sum':'mean', 'Owner_sum':'mean', 'Renter_sum':'mean',
       'discount_rate_mean':'mean', 'total_appartments':'mean', 'discount_percent':'mean',
       'Low_discount':'mean', 'High_discount':'mean', 'No_discount':'mean', 'Owner_Percent':'mean',
       'houseHold2':'mean'}).reset_index()

In [64]:
studyGBAgg.head()

,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
0,20100133,1,2.0,57.0,19.0,2.0,98.0,48.0,24.0,16.0,26,16.0,46.0,25.806452,90.0,77.0,70.0,70.0,8.0,12.0,8.0,4.0,4.0,10.0,6.0,0.480824,16.0,0.750000,0.250000,0.500000,0.250000,0.625000,3.875000
1,20110270,1,2.0,55.0,21.0,24.0,90.0,66.0,17.0,18.0,33,20.0,15.0,57.142857,90.0,74.0,60.0,80.0,10.0,12.0,8.0,4.0,6.0,13.0,5.0,0.363162,18.0,0.666667,0.222222,0.444444,0.333333,0.722222,1.944444
2,20120894,1,2.0,50.0,10.0,2.0,94.0,39.0,23.0,16.0,24,7.0,33.0,17.500000,90.0,70.0,60.0,60.0,12.0,5.0,1.0,4.0,11.0,14.0,2.0,0.073787,16.0,0.312500,0.250000,0.062500,0.687500,0.875000,2.500000
3,20131419,1,2.0,44.0,14.0,10.0,98.0,46.0,19.0,15.0,29,10.0,41.0,19.607843,90.0,78.0,40.0,90.0,16.0,4.0,2.0,2.0,11.0,13.0,2.0,0.107741,15.0,0.266667,0.133333,0.133333,0.733333,0.866667,3.400000
4,20140060,1,2.0,50.0,13.0,4.0,96.0,40.0,25.0,15.0,27,12.0,38.0,24.000000,100.0,82.0,70.0,70.0,12.0,6.0,4.0,2.0,9.0,9.0,6.0,0.218468,15.0,0.400000,0.133333,0.266667,0.600000,0.600000,3.333333

In [65]:
studyGBAgg = studyGBAgg.astype({"plan_num": str})

In [66]:
script = script.astype({"ProjNumber":str})

In [67]:
scriptWithStudy = pd.merge(script,studyGBAgg, how='left',left_on='ProjNumber',right_on='plan_num')

In [68]:
scriptWithStudy

,Unnamed: 0,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
0,15,210_19,210_19_a,1,20180988,1,1,17,20180988,1.0,2.000000,35.000000,9.000000,5.000000,82.000000,45.000000,19.000000,20.000000,41.0,8.000000,47.000000,14.545455,80.000000,63.000000,30.000000,70.000000,16.000000,5.000000,4.000000,1.000000,15.000000,12.000000,8.000000,0.150829,20.000000,0.250000,0.050000,0.200000,0.750000,0.600000,2.750000
1,16,210_14,210_14_a,1,20100133,2,2,18,20100133,1.0,2.000000,57.000000,19.000000,2.000000,98.000000,48.000000,24.000000,16.000000,26.0,16.000000,46.000000,25.806452,90.000000,77.000000,70.000000,70.000000,8.000000,12.000000,8.000000,4.000000,4.000000,10.000000,6.000000,0.480824,16.000000,0.750000,0.250000,0.500000,0.250000,0.625000,3.875000
2,14,208_32,208_32_a,1,20180812,3,3,19,20180812,1.0,2.000000,33.000000,10.000000,5.000000,89.000000,46.000000,23.000000,17.000000,34.0,11.000000,24.000000,31.428571,90.000000,62.000000,30.000000,50.000000,17.000000,7.000000,4.000000,3.000000,10.000000,10.000000,7.000000,0.284133,17.000000,0.411765,0.176471,0.235294,0.588235,0.588235,2.058824
3,19,210_3,210_3_a,1,20181092,4,4,20,20181092,1.0,2.000000,54.000000,15.000000,2.000000,99.000000,45.000000,26.000000,16.000000,30.0,17.000000,42.000000,28.813559,80.000000,80.000000,80.000000,80.000000,0.000000,7.000000,6.000000,1.000000,9.000000,10.000000,6.000000,0.285945,16.000000,0.437500,0.062500,0.375000,0.562500,0.625000,3.687500
4,20,210_35,210_35_r,2,20171974,5,20,13,20171974,1.0,2.000000,43.000000,10.000000,3.000000,90.000000,46.000000,23.000000,13.000000,43.0,14.000000,39.000000,26.415094,100.000000,66.000000,30.000000,60.000000,16.000000,5.000000,3.000000,2.000000,8.000000,8.000000,5.000000,0.243069,13.000000,0.384615,0.153846,0.230769,0.615385,0.615385,4.076923
5,17,210_12,210_12_a,1,20180345,6,5,21,20180345,1.0,2.000000,48.000000,17.000000,3.000000,104.000000,55.000000,20.000000,39.000000,48.0,38.000000,60.000000,38.775510,90.000000,69.000000,40.000000,80.000000,15.000000,18.000000,10.000000,8.000000,21.000000,27.000000,12.000000,0.226707,39.000000,0.461538,0.205128,0.256410,0.538462,0.692308,2.512821
6,18,210_10,210_10_a,1,20140556,7,6,22,20140556,1.0,2.000000,54.000000,15.000000,2.000000,109.000000,50.000000,24.000000,61.000000,90.0,55.000000,99.000000,35.714286,80.000000,62.000000,40.000000,70.000000,9.000000,30.000000,18.000000,12.000000,31.000000,39.000000,22.000000,0.296857,61.000000,0.491803,0.196721,0.295082,0.508197,0.639344,2.524590
7,22,"211_19,211_20,211_19","211_22_r,211_20_r,211_19_r",2,20170076,8,21,14,20170076,1.0,2.000000,12.000000,6.000000,2.000000,72.000000,27.000000,26.000000,4.000000,55.0,2.000000,6.000000,25.000000,70.000000,57.000000,50.000000,50.000000,9.000000,2.000000,2.000000,0.000000,2.000000,2.000000,2.000000,0.500000,4.000000,0.500000,0.000000,0.500000,0.500000,0.500000,2.000000
8,26,"224_3,220_7,220_3,210_34,210_36,220_5,210_32_2...","220_3_224_3_rr,210_30_210_32_rr,220_5_rr,220_7...",3,502-0196659,9,24,1,502-0196659,8.0,2.125000,48.875000,15.875000,4.375000,98.875000,47.875000,23.625000,20.250000,497.0,18.375000,43.375000,29.204431,128.750000,77.000000,53.750000,73.750000,20.625000,8.750000,5.750000,3.000000,11.375000,10.375000,9.750000,0.258501,20.125000,0.435034,0.160623,0.274411,0.564966,0.544690,3.097580
9,21,215_6,215_6_r,2,20150857,10,22,15,20150857,1.0,2.000000,58.000000,14.000000,2.000000,104.000000,45.000000,26.000000,12.000000,39.0,12.000000,30.000000,28.571429,100.000000,88.000000,60.000000,90.000000,14.000000,6.000000,3.000000,3.000000,6.000000,8.000000,4.000000,0.254921,12.000000,0.500000,0.250000,0.250000,0.500000,0.666667,3.500000
10,33,"221_4_221_2,221_6","216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1,216_4,216_4_a,1,20141086,12,7,23,20141086,1.0,2.000000,45.000000,9.000000,2.000000,97.000000,45.000000,24.000000,18.000000,18.0,15.000000,40.000000,27.272727,180.000000,94.000000,60.000000,80.000000,35.000000,8.000000,7.000000,1.000000,10.000000,6.000000,12.000000,0.314753,18.000000,0.444444,0.055556,0.388889,0.555556,0.333333,3.055556
12,2,209_6,209_6_r,2,20140231,13,23,16,20140231,1.0,5.000000,26.000000,13.000000,5.000000,94.000000,35.000000,24.000000,6.000000,28.0,3.000000,18.000000,14.285714,90.000000,90.000000,90.000000,90.000000,0.000000,5.000000,5.000000,0.000000,1.000000,6.000000,0.000000,0.375612,6.000000,0.833333,0.000000,0.833333,0.166667,1.000000,3.500000
13,0,215_22,215_22_a,1,20140882,14,8,24,20140882,1.0,2.000000,47.000000,12.000000,3.000000,97.000000,45.000000,24.000000,32.000000,33.0,17.000000,56.000000,23.287671,180.000000,83.000000,60.000000,70.000000,25.000000,12.000000,8.000000,4.000000,20.000000,25.000000,7.000000,0.210411,32.000000,0.375000,0.125000,0.250000,0.625000,0.781250,2.281250
14,5,210_11,210_11_a,1,20150274,15,9,25,20150274,1.0,2.000000,51.000000,17.000000,2.000000,89.000000,40.000000,23.000000,12.000000,20.0,5.000000,29.000000,14.705882,90.000000,79.000000,60.000000,80.000000,9.000000,3.000000,2.000000,1.000000,9.000000,8.000000,4.000000,0.187500,12.000000,0.250000,0.083333,0.166667,0.750000,0.666667,2.833333
15,6,216_3,216_3_a,1,20141190,16,10,26,20141190,1.0,2.000000,56.000000,19.000000,5.000000,94.000000,49.000000,22.000000,36.000000,32.0,32.000000,78.000000,29.090909,200.000000,77.000000,50.000000,70.000000,29.000000,15.000000,7.000000,8.000000,20.000000,25.000000,10.000000,0.187275,35.000000,0.428571,0.228571,0.200000,0.571429,0.714286,3.142857
16,3,209_8_209_10_209_12,209_8_209_10_209_12_a,1,20120894,17,11,27,20120894,1.0,2.000000,50.000000,10.000000,2.000000,94.000000,39.000000,23.000000,16.000000,24.0,7.000000,33.000000,17.500000,90.000000,70.000000,60.000000,60.000000,12.000000,5.000000,1.000000,4.000000,11.000000,14.000000,2.000000,0.073787,16.000000,0.312500,0.250000,0.062500,0.687500,0.875000,2.500000
17,4,208_12,208_12_a,1,20181295,18,12,28,20181295,1.0,2.000000,49.000000,16.000000,2.000000,109.000000,53.000000,25.000000,24.000000,51.0,22.000000,34.000000,39.285714,110.000000,83.000000,80.000000,80.000000,10.000000,16.000000,8.000000,8.000000,8.000000,17.000000,7.000000,0.348805,24.000000,0.666667,0.333333,0.333333,0.333333,0.708333,2.333333
18,9,220_4,220_4_a,1,20131419,19,13,29,20131419,1.0,2.000000,44.000000,14.000000,10.000000,98.000000,46.000000,19.000000,15.000000,29.0,10.000000,41.000000,19.607843,90.000000,78.000000,40.000000,90.000000,16.000000,4.000000,2.000000,2.000000,11.000000,13.000000,2.000000,0.107741,15.000000,0.266667,0.133333,0.133333,0.733333,0.866667,3.400000
19,7,215_18,215_18_a,1,20140060,20,14,30,20140060,1.0,2.000000,50.000000,13.000000,4.000000,96.000000,40.000000,25.000000,15.000000,27.0,12.000000,38.000000,24.000000,100.000000,82.000000,70.000000,70.000000,12.000000,6.000000,4.000000,2.000000,9.000000,9.000000,6.000000,0.218468,15.000000,0.400000,0.133333,0.266667,0.600000,0.600000,3.333333
20,8,215_24,215_24_a,1,20110270,21,15,31,20110270,1.0,2.000000,55.000000,21.000000,24.000000,90.000000,66.000000,17.000000,18.000000,33.0,20.000000,15.000000,57.142857,90.000000,74.000000,60.000000,80.000000,10.000000,12.000000,8.000000,4.000000,6.000000,13.000000,5.000000,0.363162,18.000000,0.666667,0.222222,0.444444,0.333333,0.722222,1.944444
21,12,209_4,209_4_a,1,20180845,22,16,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,13,217_5,217_5_a,1,20140467,23,17,33,20140467,1.0,2.000000,59.000000,19.000000,10.000000,92.000000,50.000000,23.000000,16.000000,27.0,17.000000,30.000000,36.170213,90.000000,77.000000,50.000000,90.000000,13.000000,8.000000,7.000000,1.000000,8.000000,10.000000,6.000000,0.344729,16.000000,0.500000,0.062500,0.437500,0.500000,0.625000,2.937500
23,10,212_53,212_53_a,1,20160319,24,18,34,20160319,1.0,2.000000,52.000000,18.000000,11.000000,97.000000,58.000000,21.000000,33.000000,38.0,36.000000,40.000000,47.368421,200.000000,84.000000,70.000000,90.000000,22.000000,19.000000,10.000000,9.000000,14.000000,26.000000,7.000000,0.318202,33.000000,0.575758,0.272727,0.303030,0.424242,0.787879,2.303030
24,11,209_29,209_29_a,1,20141182,25,19,35,20141182,1.0,2.000000,48.000000,17.000000,9.000000,96.000000,55.000000,23.000000,12.000000,28.0,13.000000,25.000000,34.210526,100.000000,87.000000,70.000000,100.000000,13.000000,7.000000,5.000000,2.000000,5.000000,7.000000,5.000000,0.308843,12.000000,0.583333,0.166667,0.416667,0.416667,0.583333,3.166667
25,34,201_75,201_75_rr,3,502-0368860,26,26,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,23,"212_61,212_61,212_61,216_8","212_59_rr,212_61_1_rr,212_61_rr",3,502-0654715,27,27,4,502-0654715,3.0,2.000000,50.666667,17.666667,2.333333,104.666667,49.666667,25.666667,32.666667,284.0,37.666667,65.000000,33.289811,123.333333,91.666667,76.666667,90.000000,15.000000,12.666667,7.333333,5.333333,19.666667,21.666667,10.666667,0.175878,32.333333,0.443831,0.281385,0.162446,0.556169,0.607413,3.222727
27,29,"209_30,209_32,209_30,209_32","209_32_1_rr,209_32_rr",3,502-0316752,28,28,5,502-0316752,2.0,5.500000,12.500000,7.500000,13.500000,59.500000,39.500000,17.000000,1.500000,70.0,0.500000,7.500000,3.571429,100.000000,97.500000,95.000000,95.000000,3.500000,0.000000,0.000000,0.000000,1.500000,0.000000,1.500000,0.000000,1.500000,0.000000,0.000000,0.000000,1.000000,0.000000,4.500000
28,27,"215_12,215_14,102_3,215_12","215_14_rr,215_14_102_3_215_12_rr",3,502-0201483,29,29,6,502-0201483,3.0,2.000000,52.000000,18.000000,9.666667,98.666667,51.666667,23.000000,17.000000,169.0,17.666667,35.333333,33.559322,116.666667,85.666667,60.000000,83.333333,15.000000,8.000000,4.666667,3.333333,9.000000,11.333333,5.666667,0.223397,17.000000,0.460752,0.184461,0.276291,0.539248,0.701153,3.744060
29,25,212_63,"212_63_rr,212_63_1_rr",3,502-0583948,30,30,7,502-0583948,1.0,2.000000,28.000000,8.000000,3.000000,88.000000,42.000000,22.000000,9.000000,52.0,5.000000,22.000000,18.518519,240.000000,121.000000,100.000000,100.000000,45.000000,3.000000,1.000000,2.000000,6.000000,7.000000,2.000000,0.151063,9.000000,0.333333,0.222222,0.111111,0.666667,0.777778,3.000000
30,24,"201_7,201_9,201_9,201_9","201_7_rr,201_9_rr",3,502-0424911,31,31,8,502-0424911,1.0,6.000000,56.000000,20.000000,9.000000,102.000000,50.000000,29.000000,9.000000,69.0,5.000000,10.000000,33.333333,130.000000,80.000000,30.000000,80.000000,25.000000,4.000000,2.000000,2.000000,5.000000,4.000000,5.000000,0.224987,9.000000,0.444444,0.222222,0.222222,0.555556,0.444444,1.666667
31,28,220_4,"215_2_rr,220_2_rr",3,502-0147678,32,32,9,502-0147678,2.0,3.500000,35.000000,17.500000,10.000000,99.000000,53.000000,23.000000,12.000000,80.0,6.500000,12.000000,32.453416,105.000000,94.000000,80.000000,90.000000,12.000000,1.500000,1.500000,0.000000,2.000000,3.500000,0.000000,0.290009,3.500000,0.300000,0.000000,0.300000,0.700000,1.000000,5.800000
32,30,"225_8,225_6,210_8,225_6","225_6_rr,225_8_rr",3,502-0178285,33,33,10,502-0178285,3.0,2.000000,54.666667,16.333333,4.000000,89.333333,48.000000,21.333333,28.000000,331.0,23.666667,57.666667,29.582747,96.666667,60.333333,43.333333,60.000000,10.333333,13.000000,9.666667,3.333333,15.000000,15.666667,12.333333,0.343599,28.000000,0.473545,0.084656,0.388889,0.526455,0.591270,5.183862
33,31,"211_9,210_18,210_16,211_11,211_7","210_18_rr,211_11_rr",3,502-0317495,34,34,11,502-0317495,3.0,2.333333,37.000000,11.333333,14.333333,72.666667,46.333333,17.666667,14.333333,210.0,6.666667,15.000000,21.880342,83.333333,70.666667,46.666667,66.666667,12.666667,6.666667,3.333333,3.333333,7.666667,9.000000,5.333333,0.239939,14.333333,0.473684,0.236842,0.236842,0.526316,0.627193,1.406433
34,32,"221_30_211_26,211_25_211_27_211_29,221_22","221_22_221_29_rr,211_30_211_26_rr,211_27_rr",3,502-0189720,35,35,12,502-0189720,5.0,8.200000,31.200000,14.800000,11.200000,79.000000,48.200000,20.400000,9.200000,138.0,5.400000,10.800000,22.200000,76.000000,66.000000,58.000000,64.000000,6.000000,3.800000,3.000000,0.800000,5.400000,4.800000,4.400000,0.301113,9.200000,0.426667,0.047222,0.379444,0.573333,0.480000,3.065556

In [69]:
scriptWithStudy[scriptWithStudy['plan_num'].isnull()]

,Unnamed: 0,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
10,33,"221_4_221_2,221_6","216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,12,209_4,209_4_a,1,20180845,22,16,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,34,201_75,201_75_rr,3,502-0368860,26,26,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
ArticleStat = scriptWithStudy[~scriptWithStudy['plan_num'].isnull()]

In [71]:
ArticleStat.columns

Index(['Unnamed: 0', 'BeforeBldgs', 'AfterBldgs', 'ProjType', 'ProjNumber',
       'OrderA', 'OrderB', 'OrderC', 'plan_num', 'Row Labels',
       'min_living_till_2020', 'max_living_till_2020', 'avg_living_till_2020',
       'Min_age_2020', 'Max_age_2020', 'Average_age_2020', 'StdDev_age_2020',
       'Before_app', 'after_app', 'Above_65', 'Under_65', 'percent_above_65',
       'Area_round_max', 'Area_round_mean', 'Area_round_min',
       'Area_round_mode', 'Area_round_std', 'Discount_sum',
       'High_discount_sum', 'Low_Discount_35_sum', 'No_Discount_sum',
       'Owner_sum', 'Renter_sum', 'discount_rate_mean', 'total_appartments',
       'discount_percent', 'Low_discount', 'High_discount', 'No_discount',
       'Owner_Percent', 'houseHold2'],
      dtype='object')

## Now I run statistics

In [72]:
ArticleStat.agg({'min_living_till_2020':['mean'], 'max_living_till_2020':['mean']})

      min_living_till_2020  max_living_till_2020
mean              2.583073             44.747135

In [73]:
ArticleStat.agg({'min_living_till_2020':['mean'], 'max_living_till_2020':['mean'], 'avg_living_till_2020':['mean','std'],
       'Min_age_2020':['mean'], 'Max_age_2020':['mean'], 'Average_age_2020':['mean','std'], 'StdDev_age_2020':['mean'],
       'percent_above_65':['mean','std'],
       'Area_round_max':['mean'], 'Area_round_mean':['mean','std'], 'Area_round_min':['mean'],
       'Area_round_mode':['mean'], 'Area_round_std':['mean'], 'Discount_sum':['mean'],
       'High_discount_sum':['mean'], 'Low_Discount_35_sum':['mean'], 'No_Discount_sum':['mean'],
       'Owner_sum':['sum'], 'Renter_sum':['sum'], 'discount_rate_mean':['mean','std'], 'total_appartments':['sum','count'],
       'discount_percent':['mean','std'], 'Low_discount':['mean','std'], 'High_discount':['mean','std'], 'No_discount':['mean','std'],
       'Owner_Percent':['mean','std'],'houseHold2':['mean','std']}).apply(lambda x:round(x,2))

,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
mean,2.58,44.75,14.38,6.14,93.18,47.01,22.71,28.02,112.18,78.93,59.17,77.27,14.85,8.54,5.32,3.22,10.02,NaN,NaN,0.26,NaN,0.45,0.15,0.29,0.55,0.64,3.08
std,NaN,NaN,4.05,NaN,NaN,7.09,NaN,10.31,NaN,13.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.11,NaN,0.16,0.09,0.15,0.16,0.19,0.95
sum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,392.34,201.65,NaN,593.99,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.00,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
pd.options.display.max_columns=100

In [75]:
ArticleMissing = scriptWithStudy[scriptWithStudy['plan_num'].isnull()].copy()

In [76]:
ArticleMissing

,Unnamed: 0,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
10,33,"221_4_221_2,221_6","216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,12,209_4,209_4_a,1,20180845,22,16,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,34,201_75,201_75_rr,3,502-0368860,26,26,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
from_ = ArticleStat.columns.tolist().index('min_living_till_2020')

In [78]:
columnsStat = ArticleStat.columns[from_:].tolist()

In [79]:
statsRef = ArticleStat[columnsStat].agg(['mean','std']).apply(lambda x: round(x,1))

In [80]:
statsRef

,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
mean,2.6,44.7,14.4,6.1,93.2,47.0,22.7,18.9,84.2,15.9,35.9,28.0,112.2,78.9,59.2,77.3,14.8,8.5,5.3,3.2,10.0,12.3,6.3,0.3,18.6,0.4,0.2,0.3,0.6,0.6,3.1
std,1.5,12.4,4.1,5.0,10.8,7.1,2.8,12.0,106.9,12.4,21.1,10.3,41.8,13.2,19.0,13.4,9.4,6.2,3.7,2.9,6.7,8.5,4.4,0.1,12.2,0.2,0.1,0.2,0.2,0.2,1.0

In [81]:
ArticleMissing.reset_index(inplace=True)

In [82]:
ArticleMissing = ArticleMissing.drop(columns={'index'})

In [83]:
for col in columnsStat:
    ArticleMissing[col] =ArticleMissing.apply(lambda x: statsRef[col]['mean']+(np.random.rand()-0.5)*2*statsRef[col]['std'],axis = 1)

In [84]:
ArticleMissing.iloc[:,2:]

,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
0,"216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2,NaN,NaN,3.034494,42.277741,12.496582,3.640933,85.216980,53.307495,25.205947,29.583756,21.112107,22.979817,56.453747,17.933179,138.284957,84.249697,59.275692,68.597426,15.739572,3.463875,6.346420,2.572850,11.297380,10.030725,4.499744,0.377727,19.463017,0.262629,0.112947,0.482004,0.689719,0.466555,3.332648
1,209_4_a,1,20180845,22,16,32,NaN,NaN,1.528627,32.646338,11.582384,6.844482,83.357566,50.328780,22.365085,22.882483,138.945675,15.860325,40.095408,20.586708,95.996652,86.267141,76.753637,86.430530,7.615565,10.405044,1.933758,4.400782,10.606053,18.928480,6.758559,0.261629,22.415725,0.527710,0.233112,0.204653,0.428229,0.589800,3.995937
2,201_75_rr,3,502-0368860,26,26,3,NaN,NaN,1.507670,40.064271,13.656463,2.743948,93.555792,45.047362,22.626458,7.615784,65.473676,4.944792,24.857197,23.673719,81.792247,70.309373,69.610421,87.254877,8.187810,9.500606,7.756946,3.553614,3.419025,4.122822,4.718750,0.268917,29.487131,0.272619,0.138385,0.397476,0.536115,0.439184,2.348359

In [85]:
ArticleStat.iloc[:,1:].head(2)

,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,after_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent,houseHold2
0,210_19,210_19_a,1,20180988,1,1,17,20180988,1.0,2.0,35.0,9.0,5.0,82.0,45.0,19.0,20.0,41.0,8.0,47.0,14.545455,80.0,63.0,30.0,70.0,16.0,5.0,4.0,1.0,15.0,12.0,8.0,0.150829,20.0,0.25,0.05,0.2,0.75,0.600,2.750
1,210_14,210_14_a,1,20100133,2,2,18,20100133,1.0,2.0,57.0,19.0,2.0,98.0,48.0,24.0,16.0,26.0,16.0,46.0,25.806452,90.0,77.0,70.0,70.0,8.0,12.0,8.0,4.0,4.0,10.0,6.0,0.480824,16.0,0.75,0.25,0.5,0.25,0.625,3.875

In [86]:
ArticleStat = pd.concat([ArticleStat,ArticleMissing]).reset_index(drop=True)

In [87]:
ArticleStat = ArticleStat.iloc[:,1:-1]

In [89]:
ArticleStat.to_excel('BuildingInSimulationAndStatsApril6.xlsx')

In [35]:
ArticleMissing.columns

Index(['Unnamed: 0', 'BeforeBldgs', 'AfterBldgs', 'ProjType', 'ProjNumber',
       'OrderA', 'OrderB', 'OrderC', 'plan_num', 'Row Labels',
       'min_living_till_2020', 'max_living_till_2020', 'avg_living_till_2020',
       'Min_age_2020', 'Max_age_2020', 'Average_age_2020', 'StdDev_age_2020',
       'Before_app', 'Above_65', 'Under_65', 'percent_above_65',
       'Area_round_max', 'Area_round_mean', 'Area_round_min',
       'Area_round_mode', 'Area_round_std', 'Discount_sum',
       'High_discount_sum', 'Low_Discount_35_sum', 'No_Discount_sum',
       'Owner_sum', 'Renter_sum', 'discount_rate_mean', 'total_appartments',
       'discount_percent', 'Low_discount', 'High_discount', 'No_discount',
       'Owner_Percent', 'houseHold2'],
      dtype='object')

In [31]:
ArticleStat'min_living_till_2020', 'max_living_till_2020', 'avg_living_till_2020',
       'Min_age_2020', 'Max_age_2020', 'Average_age_2020', 'StdDev_age_2020',
       'Before_app', 'Above_65', 'Under_65', 'percent_above_65',
       'Area_round_max', 'Area_round_mean', 'Area_round_min',
       'Area_round_mode', 'Area_round_std', 'Discount_sum',
       'High_discount_sum', 'Low_Discount_35_sum', 'No_Discount_sum',
       'Owner_sum', 'Renter_sum', 'discount_rate_mean', 'total_appartments',
       'discount_percent', 'Low_discount', 'High_discount', 'No_discount',
       'Owner_Percent', 'houseHold2'

SyntaxError: invalid syntax (<ipython-input-31-cff54bcc0bf5>, line 1)

In [37]:
ArticleStat

,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent
0,210_19,210_19_a,1,20180988,1,1,17,20180988,1.0,2.000000,35.000000,9.000000,5.000000,82.000000,45.000000,19.000000,20.000000,8.000000,47.000000,14.545455,80.000000,63.000000,30.000000,70.000000,16.000000,5.000000,4.000000,1.000000,15.000000,12.000000,8.000000,0.150829,20.000000,0.250000,0.050000,0.200000,0.750000,0.600000
1,210_14,210_14_a,1,20100133,2,2,18,20100133,1.0,2.000000,57.000000,19.000000,2.000000,98.000000,48.000000,24.000000,16.000000,16.000000,46.000000,25.806452,90.000000,77.000000,70.000000,70.000000,8.000000,12.000000,8.000000,4.000000,4.000000,10.000000,6.000000,0.480824,16.000000,0.750000,0.250000,0.500000,0.250000,0.625000
2,208_32,208_32_a,1,20180812,3,3,19,20180812,1.0,2.000000,33.000000,10.000000,5.000000,89.000000,46.000000,23.000000,17.000000,11.000000,24.000000,31.428571,90.000000,62.000000,30.000000,50.000000,17.000000,7.000000,4.000000,3.000000,10.000000,10.000000,7.000000,0.284133,17.000000,0.411765,0.176471,0.235294,0.588235,0.588235
3,210_3,210_3_a,1,20181092,4,4,20,20181092,1.0,2.000000,54.000000,15.000000,2.000000,99.000000,45.000000,26.000000,16.000000,17.000000,42.000000,28.813559,80.000000,80.000000,80.000000,80.000000,0.000000,7.000000,6.000000,1.000000,9.000000,10.000000,6.000000,0.285945,16.000000,0.437500,0.062500,0.375000,0.562500,0.625000
4,210_35,210_35_r,2,20171974,5,20,13,20171974,1.0,2.000000,43.000000,10.000000,3.000000,90.000000,46.000000,23.000000,13.000000,14.000000,39.000000,26.415094,100.000000,66.000000,30.000000,60.000000,16.000000,5.000000,3.000000,2.000000,8.000000,8.000000,5.000000,0.243069,13.000000,0.384615,0.153846,0.230769,0.615385,0.615385
5,210_12,210_12_a,1,20180345,6,5,21,20180345,1.0,2.000000,48.000000,17.000000,3.000000,104.000000,55.000000,20.000000,39.000000,38.000000,60.000000,38.775510,90.000000,69.000000,40.000000,80.000000,15.000000,18.000000,10.000000,8.000000,21.000000,27.000000,12.000000,0.226707,39.000000,0.461538,0.205128,0.256410,0.538462,0.692308
6,210_10,210_10_a,1,20140556,7,6,22,20140556,1.0,2.000000,54.000000,15.000000,2.000000,109.000000,50.000000,24.000000,61.000000,55.000000,99.000000,35.714286,80.000000,62.000000,40.000000,70.000000,9.000000,30.000000,18.000000,12.000000,31.000000,39.000000,22.000000,0.296857,61.000000,0.491803,0.196721,0.295082,0.508197,0.639344
7,"211_19,211_20,211_19","211_22_r,211_20_r,211_19_r",2,20170076,8,21,14,20170076,1.0,2.000000,12.000000,6.000000,2.000000,72.000000,27.000000,26.000000,4.000000,2.000000,6.000000,25.000000,70.000000,57.000000,50.000000,50.000000,9.000000,2.000000,2.000000,0.000000,2.000000,2.000000,2.000000,0.500000,4.000000,0.500000,0.000000,0.500000,0.500000,0.500000
8,"224_3,220_7,220_3,210_34,210_36,220_5,210_32_2...","220_3_224_3_rr,210_30_210_32_rr,220_5_rr,220_7...",3,502-0196659,9,24,1,502-0196659,8.0,2.125000,48.875000,15.875000,4.375000,98.875000,47.875000,23.625000,20.250000,18.375000,43.375000,29.204431,128.750000,77.000000,53.750000,73.750000,20.625000,8.750000,5.750000,3.000000,11.375000,10.375000,9.750000,0.258501,20.125000,0.435034,0.160623,0.274411,0.564966,0.544690
9,215_6,215_6_r,2,20150857,10,22,15,20150857,1.0,2.000000,58.000000,14.000000,2.000000,104.000000,45.000000,26.000000,12.000000,12.000000,30.000000,28.571429,100.000000,88.000000,60.000000,90.000000,14.000000,6.000000,3.000000,3.000000,6.000000,8.000000,4.000000,0.254921,12.000000,0.500000,0.250000,0.250000,0.500000,0.666667
10,216_4,216_4_a,1,20141086,12,7,23,20141086,1.0,2.000000,45.000000,9.000000,2.000000,97.000000,45.000000,24.000000,18.000000,15.000000,40.000000,27.272727,180.000000,94.000000,60.000000,80.000000,35.000000,8.000000,7.000000,1.000000,10.000000,6.000000,12.000000,0.314753,18.000000,0.444444,0.055556,0.388889,0.555556,0.333333
11,209_6,209_6_r,2,20140231,13,23,16,20140231,1.0,5.000000,26.000000,13.000000,5.000000,94.000000,35.000000,24.000000,6.000000,3.000000,18.000000,14.285714,90.000000,90.000000,90.000000,90.000000,0.000000,5.000000,5.000000,0.000000,1.000000,6.000000,0.000000,0.375612,6.000000,0.833333,0.000000,0.833333,0.166667,1.000000
12,215_22,215_22_a,1,20140882,14,8,24,20140882,1.0,2.000000,47.000000,12.000000,3.000000,97.000000,45.000000,24.000000,32.000000,17.000000,56.000000,23.287671,180.000000,83.000000,60.000000,70.000000,25.000000,12.000000,8.000000,4.000000,20.000000,25.000000,7.000000,0.210411,32.000000,0.375000,0.125000,0.250000,0.625000,0.781250
13,210_11,210_11_a,1,20150274,15,9,25,20150274,1.0,2.000000,51.000000,17.000000,2.000000,89.000000,40.000000,23.000000,12.000000,5.000000,29.000000,14.705882,90.000000,79.000000,60.000000,80.000000,9.000000,3.000000,2.000000,1.000000,9.000000,8.000000,4.000000,0.187500,12.000000,0.250000,0.083333,0.166667,0.750000,0.666667
14,216_3,216_3_a,1,20141190,16,10,26,20141190,1.0,2.000000,56.000000,19.000000,5.000000,94.000000,49.000000,22.000000,36.000000,32.000000,78.000000,29.090909,200.000000,77.000000,50.000000,70.000000,29.000000,15.000000,7.000000,8.000000,20.000000,25.000000,10.000000,0.187275,35.000000,0.428571,0.228571,0.200000,0.571429,0.714286
15,209_8_209_10_209_12,209_8_209_10_209_12_a,1,20120894,17,11,27,20120894,1.0,2.000000,50.000000,10.000000,2.000000,94.000000,39.000000,23.000000,16.000000,7.000000,33.000000,17.500000,90.000000,70.000000,60.000000,60.000000,12.000000,5.000000,1.000000,4.000000,11.000000,14.000000,2.000000,0.073787,16.000000,0.312500,0.250000,0.062500,0.687500,0.875000
16,208_12,208_12_a,1,20181295,18,12,28,20181295,1.0,2.000000,49.000000,16.000000,2.000000,109.000000,53.000000,25.000000,24.000000,22.000000,34.000000,39.285714,110.000000,83.000000,80.000000,80.000000,10.000000,16.000000,8.000000,8.000000,8.000000,17.000000,7.000000,0.348805,24.000000,0.666667,0.333333,0.333333,0.333333,0.708333
17,220_4,220_4_a,1,20131419,19,13,29,20131419,1.0,2.000000,44.000000,14.000000,10.000000,98.000000,46.000000,19.000000,15.000000,10.000000,41.000000,19.607843,90.000000,78.000000,40.000000,90.000000,16.000000,4.000000,2.000000,2.000000,11.000000,13.000000,2.000000,0.107741,15.000000,0.266667,0.133333,0.133333,0.733333,0.866667
18,215_18,215_18_a,1,20140060,20,14,30,20140060,1.0,2.000000,50.000000,13.000000,4.000000,96.000000,40.000000,25.000000,15.000000,12.000000,38.000000,24.000000,100.000000,82.000000,70.000000,70.000000,12.000000,6.000000,4.000000,2.000000,9.000000,9.000000,6.000000,0.218468,15.000000,0.400000,0.133333,0.266667,0.600000,0.600000
19,215_24,215_24_a,1,20110270,21,15,31,20110270,1.0,2.000000,55.000000,21.000000,24.000000,90.000000,66.000000,17.000000,18.000000,20.000000,15.000000,57.142857,90.000000,74.000000,60.000000,80.000000,10.000000,12.000000,8.000000,4.000000,6.000000,13.000000,5.000000,0.363162,18.000000,0.666667,0.222222,0.444444,0.333333,0.722222
20,217_5,217_5_a,1,20140467,23,17,33,20140467,1.0,2.000000,59.000000,19.000000,10.000000,92.000000,50.000000,23.000000,16.000000,17.000000,30.000000,36.170213,90.000000,77.000000,50.000000,90.000000,13.000000,8.000000,7.000000,1.000000,8.000000,10.000000,6.000000,0.344729,16.000000,0.500000,0.062500,0.437500,0.500000,0.625000
21,212_53,212_53_a,1,20160319,24,18,34,20160319,1.0,2.000000,52.000000,18.000000,11.000000,97.000000,58.000000,21.000000,33.000000,36.000000,40.000000,47.368421,200.000000,84.000000,70.000000,90.000000,22.000000,19.000000,10.000000,9.000000,14.000000,26.000000,7.000000,0.318202,33.000000,0.575758,0.272727,0.303030,0.424242,0.787879
22,209_29,209_29_a,1,20141182,25,19,35,20141182,1.0,2.000000,48.000000,17.000000,9.000000,96.000000,55.000000,23.000000,12.000000,13.000000,25.000000,34.210526,100.000000,87.000000,70.000000,100.000000,13.000000,7.000000,5.000000,2.000000,5.000000,7.000000,5.000000,0.308843,12.000000,0.583333,0.166667,0.416667,0.416667,0.583333
23,"212_61,212_61,212_61,216_8","212_59_rr,212_61_1_rr,212_61_rr",3,502-0654715,27,27,4,502-0654715,3.0,2.000000,50.666667,17.666667,2.333333,104.666667,49.666667,25.666667,32.666667,37.666667,65.000000,33.289811,123.333333,91.666667,76.666667,90.000000,15.000000,12.666667,7.333333,5.333333,19.666667,21.666667,10.666667,0.175878,32.333333,0.443831,0.281385,0.162446,0.556169,0.607413
24,"209_30,209_32,209_30,209_32","209_32_1_rr,209_32_rr",3,502-0316752,28,28,5,502-0316752,2.0,5.500000,12.500000,7.500000,13.500000,59.500000,39.500000,17.000000,1.500000,0.500000,7.500000,3.571429,100.000000,97.500000,95.000000,95.000000,3.500000,0.000000,0.000000,0.000000,1.500000,0.000000,1.500000,0.000000,1.500000,0.000000,0.000000,0.000000,1.000000,0.000000
25,"215_12,215_14,102_3,215_12","215_14_rr,215_14_102_3_215_12_rr",3,502-0201483,29,29,6,502-0201483,3.0,2.000000,52.000000,18.000000,9.666667,98.666667,51.666667,23.000000,17.000000,17.666667,35.333333,33.559322,116.666667,85.666667,60.000000,83.333333,15.000000,8.000000,4.666667,3.333333,9.000000,11.333333,5.666667,0.223397,17.000000,0.460752,0.184461,0.276291,0.539248,0.701153
26,212_63,"212_63_rr,212_63_1_rr",3,502-0583948,30,30,7,502-0583948,1.0,2.000000,28.000000,8.000000,3.000000,88.000000,42.000000,22.000000,9.000000,5.000000,22.000000,18.518519,240.000000,121.000000,100.000000,100.000000,45.000000,3.000000,1.000000,2.000000,6.000000,7.000000,2.000000,0.151063,9.000000,0.333333,0.222222,0.111111,0.666667,0.777778
27,"201_7,201_9,201_9,201_9","201_7_rr,201_9_rr",3,502-0424911,31,31,8,502-0424911,1.0,6.000000,56.000000,20.000000,9.000000,102.000000,50.000000,29.000000,9.000000,5.000000,10.000000,33.333333,130.000000,80.000000,30.000000,80.000000,25.000000,4.000000,2.000000,2.000000,5.000000,4.000000,5.000000,0.224987,9.000000,0.444444,0.222222,0.222222,0.555556,0.444444
28,220_4,"215_2_rr,220_2_rr",3,502-0147678,32,32,9,502-0147678,2.0,3.500000,35.000000,17.500000,10.000000,99.000000,53.000000,23.000000,12.000000,6.500000,12.000000,32.453416,105.000000,94.000000,80.000000,90.000000,12.000000,1.500000,1.500000,0.000000,2.000000,3.500000,0.000000,0.290009,3.500000,0.300000,0.000000,0.300000,0.700000,1.000000
29,"225_8,225_6,210_8,225_6","225_6_rr,225_8_rr",3,502-0178285,33,33,10,502-0178285,3.0,2.000000,54.666667,16.333333,4.000000,89.333333,48.000000,21.333333,28.000000,23.666667,57.666667,29.582747,96.666667,60.333333,43.333333,60.000000,10.333333,13.000000,9.666667,3.333333,15.000000,15.666667,12.333333,0.343599,28.000000,0.473545,0.084656,0.388889,0.526455,0.591270
30,"211_9,210_18,210_16,211_11,211_7","210_18_rr,211_11_rr",3,502-0317495,34,34,11,502-0317495,3.0,2.333333,37.000000,11.333333,14.333333,72.666667,46.333333,17.666667,14.333333,6.666667,15.000000,21.880342,83.333333,70.666667,46.666667,66.666667,12.666667,6.666667,3.333333,3.333333,7.666667,9.000000,5.333333,0.239939,14.333333,0.473684,0.236842,0.236842,0.526316,0.627193
31,"221_30_211_26,211_25_211_27_211_29,221_22","221_22_221_29_rr,211_30_211_26_rr,211_27_rr",3,502-0189720,35,35,12,502-0189720,5.0,8.200000,31.200000,14.800000,11.200000,79.000000,48.200000,20.400000,9.200000,5.400000,10.800000,22.200000,76.000000,66.000000,58.000000,64.000000,6.000000,3.800000,3.000000,0.800000,5.400000,4.800000,4.400000,0.301113,9.200000,0.426667,0.047222,0.379444,0.573333,0.480000
32,"221_4_221_2,221_6","216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2,NaN,NaN,2.082298,54.288006,10.965777,3.535115,85.004219,52.357819,23.103800,13.034541,13.055487,33.180124,28.174657,111.231514,82.182349,72.634181,70.998242,8.029904,8.417564,5.114708,5.594948,3.906666,6.069882,3.580202,0.361444,6.923456,0.459102,0.199695,0.133430,0.749588,0.503569
33,209_4,209_4_a,1,20180845,22,16,32,NaN,NaN,3.966179,35.154427,17.317810,8.326216,96.187685,52.267389,21.246819,25.771333,4.440040,35.269564,25.004784,84.765310,86.898932,46.987972,85.864765,10.089270,5.558654,1.815421,4.565270,10.710227,6.171860,9.487386,0.391027,16.369011,0.356185,0.294422,0.161147,0.715735,0.769095
34,201_75,201_75_rr,3,502-0368860,26,26,3,NaN,NaN,4.034121,49.015732,10.913240,4.926829,85.770850,47.054511,22.327388,21.695071,21.361096,33.254018,29.533309,140.744704,90.630329,49.419947,68.677672,21.055936,10.977198,5.335163,3.197578,7.578025,16.926103,5.762700,0.365601,30.366404,0.353063,0.229605,0.335453,0.699900,0.617304

In [32]:
ArticleStat

,BeforeBldgs,AfterBldgs,ProjType,ProjNumber,OrderA,OrderB,OrderC,plan_num,Row Labels,min_living_till_2020,max_living_till_2020,avg_living_till_2020,Min_age_2020,Max_age_2020,Average_age_2020,StdDev_age_2020,Before_app,Above_65,Under_65,percent_above_65,Area_round_max,Area_round_mean,Area_round_min,Area_round_mode,Area_round_std,Discount_sum,High_discount_sum,Low_Discount_35_sum,No_Discount_sum,Owner_sum,Renter_sum,discount_rate_mean,total_appartments,discount_percent,Low_discount,High_discount,No_discount,Owner_Percent
0,210_19,210_19_a,1,20180988,1,1,17,20180988,1.0,2.000000,35.000000,9.000000,5.000000,82.000000,45.000000,19.000000,20.000000,8.000000,47.000000,14.545455,80.000000,63.000000,30.000000,70.000000,16.000000,5.000000,4.000000,1.000000,15.000000,12.000000,8.000000,0.150829,20.000000,0.250000,0.050000,0.200000,0.750000,0.600000
1,210_14,210_14_a,1,20100133,2,2,18,20100133,1.0,2.000000,57.000000,19.000000,2.000000,98.000000,48.000000,24.000000,16.000000,16.000000,46.000000,25.806452,90.000000,77.000000,70.000000,70.000000,8.000000,12.000000,8.000000,4.000000,4.000000,10.000000,6.000000,0.480824,16.000000,0.750000,0.250000,0.500000,0.250000,0.625000
2,208_32,208_32_a,1,20180812,3,3,19,20180812,1.0,2.000000,33.000000,10.000000,5.000000,89.000000,46.000000,23.000000,17.000000,11.000000,24.000000,31.428571,90.000000,62.000000,30.000000,50.000000,17.000000,7.000000,4.000000,3.000000,10.000000,10.000000,7.000000,0.284133,17.000000,0.411765,0.176471,0.235294,0.588235,0.588235
3,210_3,210_3_a,1,20181092,4,4,20,20181092,1.0,2.000000,54.000000,15.000000,2.000000,99.000000,45.000000,26.000000,16.000000,17.000000,42.000000,28.813559,80.000000,80.000000,80.000000,80.000000,0.000000,7.000000,6.000000,1.000000,9.000000,10.000000,6.000000,0.285945,16.000000,0.437500,0.062500,0.375000,0.562500,0.625000
4,210_35,210_35_r,2,20171974,5,20,13,20171974,1.0,2.000000,43.000000,10.000000,3.000000,90.000000,46.000000,23.000000,13.000000,14.000000,39.000000,26.415094,100.000000,66.000000,30.000000,60.000000,16.000000,5.000000,3.000000,2.000000,8.000000,8.000000,5.000000,0.243069,13.000000,0.384615,0.153846,0.230769,0.615385,0.615385
5,210_12,210_12_a,1,20180345,6,5,21,20180345,1.0,2.000000,48.000000,17.000000,3.000000,104.000000,55.000000,20.000000,39.000000,38.000000,60.000000,38.775510,90.000000,69.000000,40.000000,80.000000,15.000000,18.000000,10.000000,8.000000,21.000000,27.000000,12.000000,0.226707,39.000000,0.461538,0.205128,0.256410,0.538462,0.692308
6,210_10,210_10_a,1,20140556,7,6,22,20140556,1.0,2.000000,54.000000,15.000000,2.000000,109.000000,50.000000,24.000000,61.000000,55.000000,99.000000,35.714286,80.000000,62.000000,40.000000,70.000000,9.000000,30.000000,18.000000,12.000000,31.000000,39.000000,22.000000,0.296857,61.000000,0.491803,0.196721,0.295082,0.508197,0.639344
7,"211_19,211_20,211_19","211_22_r,211_20_r,211_19_r",2,20170076,8,21,14,20170076,1.0,2.000000,12.000000,6.000000,2.000000,72.000000,27.000000,26.000000,4.000000,2.000000,6.000000,25.000000,70.000000,57.000000,50.000000,50.000000,9.000000,2.000000,2.000000,0.000000,2.000000,2.000000,2.000000,0.500000,4.000000,0.500000,0.000000,0.500000,0.500000,0.500000
8,"224_3,220_7,220_3,210_34,210_36,220_5,210_32_2...","220_3_224_3_rr,210_30_210_32_rr,220_5_rr,220_7...",3,502-0196659,9,24,1,502-0196659,8.0,2.125000,48.875000,15.875000,4.375000,98.875000,47.875000,23.625000,20.250000,18.375000,43.375000,29.204431,128.750000,77.000000,53.750000,73.750000,20.625000,8.750000,5.750000,3.000000,11.375000,10.375000,9.750000,0.258501,20.125000,0.435034,0.160623,0.274411,0.564966,0.544690
9,215_6,215_6_r,2,20150857,10,22,15,20150857,1.0,2.000000,58.000000,14.000000,2.000000,104.000000,45.000000,26.000000,12.000000,12.000000,30.000000,28.571429,100.000000,88.000000,60.000000,90.000000,14.000000,6.000000,3.000000,3.000000,6.000000,8.000000,4.000000,0.254921,12.000000,0.500000,0.250000,0.250000,0.500000,0.666667
10,216_4,216_4_a,1,20141086,12,7,23,20141086,1.0,2.000000,45.000000,9.000000,2.000000,97.000000,45.000000,24.000000,18.000000,15.000000,40.000000,27.272727,180.000000,94.000000,60.000000,80.000000,35.000000,8.000000,7.000000,1.000000,10.000000,6.000000,12.000000,0.314753,18.000000,0.444444,0.055556,0.388889,0.555556,0.333333
11,209_6,209_6_r,2,20140231,13,23,16,20140231,1.0,5.000000,26.000000,13.000000,5.000000,94.000000,35.000000,24.000000,6.000000,3.000000,18.000000,14.285714,90.000000,90.000000,90.000000,90.000000,0.000000,5.000000,5.000000,0.000000,1.000000,6.000000,0.000000,0.375612,6.000000,0.833333,0.000000,0.833333,0.166667,1.000000
12,215_22,215_22_a,1,20140882,14,8,24,20140882,1.0,2.000000,47.000000,12.000000,3.000000,97.000000,45.000000,24.000000,32.000000,17.000000,56.000000,23.287671,180.000000,83.000000,60.000000,70.000000,25.000000,12.000000,8.000000,4.000000,20.000000,25.000000,7.000000,0.210411,32.000000,0.375000,0.125000,0.250000,0.625000,0.781250
13,210_11,210_11_a,1,20150274,15,9,25,20150274,1.0,2.000000,51.000000,17.000000,2.000000,89.000000,40.000000,23.000000,12.000000,5.000000,29.000000,14.705882,90.000000,79.000000,60.000000,80.000000,9.000000,3.000000,2.000000,1.000000,9.000000,8.000000,4.000000,0.187500,12.000000,0.250000,0.083333,0.166667,0.750000,0.666667
14,216_3,216_3_a,1,20141190,16,10,26,20141190,1.0,2.000000,56.000000,19.000000,5.000000,94.000000,49.000000,22.000000,36.000000,32.000000,78.000000,29.090909,200.000000,77.000000,50.000000,70.000000,29.000000,15.000000,7.000000,8.000000,20.000000,25.000000,10.000000,0.187275,35.000000,0.428571,0.228571,0.200000,0.571429,0.714286
15,209_8_209_10_209_12,209_8_209_10_209_12_a,1,20120894,17,11,27,20120894,1.0,2.000000,50.000000,10.000000,2.000000,94.000000,39.000000,23.000000,16.000000,7.000000,33.000000,17.500000,90.000000,70.000000,60.000000,60.000000,12.000000,5.000000,1.000000,4.000000,11.000000,14.000000,2.000000,0.073787,16.000000,0.312500,0.250000,0.062500,0.687500,0.875000
16,208_12,208_12_a,1,20181295,18,12,28,20181295,1.0,2.000000,49.000000,16.000000,2.000000,109.000000,53.000000,25.000000,24.000000,22.000000,34.000000,39.285714,110.000000,83.000000,80.000000,80.000000,10.000000,16.000000,8.000000,8.000000,8.000000,17.000000,7.000000,0.348805,24.000000,0.666667,0.333333,0.333333,0.333333,0.708333
17,220_4,220_4_a,1,20131419,19,13,29,20131419,1.0,2.000000,44.000000,14.000000,10.000000,98.000000,46.000000,19.000000,15.000000,10.000000,41.000000,19.607843,90.000000,78.000000,40.000000,90.000000,16.000000,4.000000,2.000000,2.000000,11.000000,13.000000,2.000000,0.107741,15.000000,0.266667,0.133333,0.133333,0.733333,0.866667
18,215_18,215_18_a,1,20140060,20,14,30,20140060,1.0,2.000000,50.000000,13.000000,4.000000,96.000000,40.000000,25.000000,15.000000,12.000000,38.000000,24.000000,100.000000,82.000000,70.000000,70.000000,12.000000,6.000000,4.000000,2.000000,9.000000,9.000000,6.000000,0.218468,15.000000,0.400000,0.133333,0.266667,0.600000,0.600000
19,215_24,215_24_a,1,20110270,21,15,31,20110270,1.0,2.000000,55.000000,21.000000,24.000000,90.000000,66.000000,17.000000,18.000000,20.000000,15.000000,57.142857,90.000000,74.000000,60.000000,80.000000,10.000000,12.000000,8.000000,4.000000,6.000000,13.000000,5.000000,0.363162,18.000000,0.666667,0.222222,0.444444,0.333333,0.722222
20,217_5,217_5_a,1,20140467,23,17,33,20140467,1.0,2.000000,59.000000,19.000000,10.000000,92.000000,50.000000,23.000000,16.000000,17.000000,30.000000,36.170213,90.000000,77.000000,50.000000,90.000000,13.000000,8.000000,7.000000,1.000000,8.000000,10.000000,6.000000,0.344729,16.000000,0.500000,0.062500,0.437500,0.500000,0.625000
21,212_53,212_53_a,1,20160319,24,18,34,20160319,1.0,2.000000,52.000000,18.000000,11.000000,97.000000,58.000000,21.000000,33.000000,36.000000,40.000000,47.368421,200.000000,84.000000,70.000000,90.000000,22.000000,19.000000,10.000000,9.000000,14.000000,26.000000,7.000000,0.318202,33.000000,0.575758,0.272727,0.303030,0.424242,0.787879
22,209_29,209_29_a,1,20141182,25,19,35,20141182,1.0,2.000000,48.000000,17.000000,9.000000,96.000000,55.000000,23.000000,12.000000,13.000000,25.000000,34.210526,100.000000,87.000000,70.000000,100.000000,13.000000,7.000000,5.000000,2.000000,5.000000,7.000000,5.000000,0.308843,12.000000,0.583333,0.166667,0.416667,0.416667,0.583333
23,"212_61,212_61,212_61,216_8","212_59_rr,212_61_1_rr,212_61_rr",3,502-0654715,27,27,4,502-0654715,3.0,2.000000,50.666667,17.666667,2.333333,104.666667,49.666667,25.666667,32.666667,37.666667,65.000000,33.289811,123.333333,91.666667,76.666667,90.000000,15.000000,12.666667,7.333333,5.333333,19.666667,21.666667,10.666667,0.175878,32.333333,0.443831,0.281385,0.162446,0.556169,0.607413
24,"209_30,209_32,209_30,209_32","209_32_1_rr,209_32_rr",3,502-0316752,28,28,5,502-0316752,2.0,5.500000,12.500000,7.500000,13.500000,59.500000,39.500000,17.000000,1.500000,0.500000,7.500000,3.571429,100.000000,97.500000,95.000000,95.000000,3.500000,0.000000,0.000000,0.000000,1.500000,0.000000,1.500000,0.000000,1.500000,0.000000,0.000000,0.000000,1.000000,0.000000
25,"215_12,215_14,102_3,215_12","215_14_rr,215_14_102_3_215_12_rr",3,502-0201483,29,29,6,502-0201483,3.0,2.000000,52.000000,18.000000,9.666667,98.666667,51.666667,23.000000,17.000000,17.666667,35.333333,33.559322,116.666667,85.666667,60.000000,83.333333,15.000000,8.000000,4.666667,3.333333,9.000000,11.333333,5.666667,0.223397,17.000000,0.460752,0.184461,0.276291,0.539248,0.701153
26,212_63,"212_63_rr,212_63_1_rr",3,502-0583948,30,30,7,502-0583948,1.0,2.000000,28.000000,8.000000,3.000000,88.000000,42.000000,22.000000,9.000000,5.000000,22.000000,18.518519,240.000000,121.000000,100.000000,100.000000,45.000000,3.000000,1.000000,2.000000,6.000000,7.000000,2.000000,0.151063,9.000000,0.333333,0.222222,0.111111,0.666667,0.777778
27,"201_7,201_9,201_9,201_9","201_7_rr,201_9_rr",3,502-0424911,31,31,8,502-0424911,1.0,6.000000,56.000000,20.000000,9.000000,102.000000,50.000000,29.000000,9.000000,5.000000,10.000000,33.333333,130.000000,80.000000,30.000000,80.000000,25.000000,4.000000,2.000000,2.000000,5.000000,4.000000,5.000000,0.224987,9.000000,0.444444,0.222222,0.222222,0.555556,0.444444
28,220_4,"215_2_rr,220_2_rr",3,502-0147678,32,32,9,502-0147678,2.0,3.500000,35.000000,17.500000,10.000000,99.000000,53.000000,23.000000,12.000000,6.500000,12.000000,32.453416,105.000000,94.000000,80.000000,90.000000,12.000000,1.500000,1.500000,0.000000,2.000000,3.500000,0.000000,0.290009,3.500000,0.300000,0.000000,0.300000,0.700000,1.000000
29,"225_8,225_6,210_8,225_6","225_6_rr,225_8_rr",3,502-0178285,33,33,10,502-0178285,3.0,2.000000,54.666667,16.333333,4.000000,89.333333,48.000000,21.333333,28.000000,23.666667,57.666667,29.582747,96.666667,60.333333,43.333333,60.000000,10.333333,13.000000,9.666667,3.333333,15.000000,15.666667,12.333333,0.343599,28.000000,0.473545,0.084656,0.388889,0.526455,0.591270
30,"211_9,210_18,210_16,211_11,211_7","210_18_rr,211_11_rr",3,502-0317495,34,34,11,502-0317495,3.0,2.333333,37.000000,11.333333,14.333333,72.666667,46.333333,17.666667,14.333333,6.666667,15.000000,21.880342,83.333333,70.666667,46.666667,66.666667,12.666667,6.666667,3.333333,3.333333,7.666667,9.000000,5.333333,0.239939,14.333333,0.473684,0.236842,0.236842,0.526316,0.627193
31,"221_30_211_26,211_25_211_27_211_29,221_22","221_22_221_29_rr,211_30_211_26_rr,211_27_rr",3,502-0189720,35,35,12,502-0189720,5.0,8.200000,31.200000,14.800000,11.200000,79.000000,48.200000,20.400000,9.200000,5.400000,10.800000,22.200000,76.000000,66.000000,58.000000,64.000000,6.000000,3.800000,3.000000,0.800000,5.400000,4.800000,4.400000,0.301113,9.200000,0.426667,0.047222,0.379444,0.573333,0.480000
32,"221_4_221_2,221_6","216_6_rr,140_1_rr,300_4_rr",3,502-0316588,11,25,2,NaN,NaN,2.082298,54.288006,10.965777,3.535115,85.004219,52.357819,23.103800,13.034541,13.055487,33.180124,28.174657,111.231514,82.182349,72.634181,70.998242,8.029904,8.417564,5.114708,5.594948,3.906666,6.069882,3.580202,0.361444,6.923456,0.459102,0.199695,0.133430,0.749588,0.503569
33,209_4,209_4_a,1,20180845,22,16,32,NaN,NaN,3.966179,35.154427,17.317810,8.326216,96.187685,52.267389,21.246819,25.771333,4.440040,35.269564,25.004784,84.765310,86.898932,46.987972,85.864765,10.089270,5.558654,1.815421,4.565270,10.710227,6.171860,9.487386,0.391027,16.369011,0.356185,0.294422,0.161147,0.715735,0.769095
34,201_75,201_75_rr,3,502-0368860,26,26,3,NaN,NaN,4.034121,49.015732,10.913240,4.926829,85.770850,47.054511,22.327388,21.695071,21.361096,33.254018,29.533309,140.744704,90.630329,49.419947,68.677672,21.055936,10.977198,5.335163,3.197578,7.578025,16.926103,5.762700,0.365601,30.366404,0.353063,0.229605,0.335453,0.699900,0.617304